import{a as g,S as p,i as c}from"./assets/vendor-DjDxajEQ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const L="https://pixabay.com/api/",b="46069437-f48122ef32c6bd1c27031b929";async function m(a,e=1){const n=`${L}?key=${b}&q=${encodeURIComponent(a)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${e}`;try{return(await g.get(n)).data}catch{throw new Error("Sorry, there are no images matching your search query. Please try again!")}}const w=new p(".gallery a",{captionsData:"alt",captionDelay:200});function v({webformatURL:a,largeImageURL:e,tags:n,likes:s,views:t,comments:r,downloads:l}){return`
    <div class="card">
      <div class="card-image">
        <a href="${e}" class="gallery-item-link">
          <img src="${a}" alt="${n}" />
        </a>
      </div>
      <div class="card-body">
        <p class="card-text">Likes ${s}</p>
        <p class="card-text">Views ${t}</p>
        <p class="card-text">Comments ${r}</p>
        <p class="card-text">Downloads ${l}</p>
      </div>
    </div>`}function f(a,e,n=!1){const s=a.map(v).join("");n?e.insertAdjacentHTML("beforeend",s):e.innerHTML=s,w.refresh()}let i=1,d=null,u=0;const o={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadButton:document.querySelector(".load-button")};o.form.addEventListener("submit",S);o.loadButton.addEventListener("click",C);async function S(a){if(a.preventDefault(),d=a.currentTarget.elements.query.value.trim(),d===""){c.show({title:"Oops",message:"Sorry, there are no images matching your search query. Please try again!",color:"#ef4040",position:"bottomCenter"});return}i=1,o.gallery.innerHTML="",o.loadButton.classList.add("hidden"),h();try{const e=await m(d,i);e.hits.length===0?c.show({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",color:"#ef4040",position:"bottomCenter"}):(u=e.totalHits,f(e.hits,o.gallery),u>i*15&&o.loadButton.classList.remove("hidden"))}catch{c.show({title:"Error",message:"Something went wrong. Please try again later.",color:"#ef4040",position:"bottomCenter"})}finally{y(),o.form.reset()}}async function C(a){i+=1,h();try{const e=await m(d,i);f(e.hits,o.gallery,!0),E(),u<=i*15&&(o.loadButton.classList.add("hidden"),c.show({title:"Error",message:"We're sorry, but you've reached the end of search results.",color:"#ef4040",position:"bottomCenter"}))}catch{c.show({title:"Error",message:"Something went wrong. Please try again later.",color:"#ef4040",position:"bottomCenter"})}finally{y()}}function h(){o.loader.classList.remove("hidden")}function y(){o.loader.classList.add("hidden")}function E(){const e=o.gallery.lastElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
